services:
  app:
    build:
      context: .
    volumes:
      - .:/home/jovyan/app
    ports:
      - "8000:8000"
    environment:
      JAVA_HOME: /usr/lib/jvm/java-11-openjdk-amd64
      SPARK_HOME: /opt/spark
    command: ["sh", "-c", "uvicorn app.main:app --host 0.0.0.0 --port 8000"]
